import type { Metadata } from "next";
import { Jost, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import { ModalStoreProvider } from "@/providers/modal-store-provider";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${jost.variable} ${montserrat.variable} ${poppins.variable}  antialiased`}
      >
        <div className="container">
          <ModalStoreProvider>{children}</ModalStoreProvider>
        </div>
      </body>
    </html>
  );
}
